activation: ReLU
alias: null
batch_size: 32
dataloader_kwargs: null
drop_last_loader: false
dropout_prob_theta: 0.6
early_stop_patience_steps: -1
exclude_insample_y: false
futr_exog_list: null
h: 84
h_train: 1
hist_exog_list: null
inference_input_size: 252
inference_windows_batch_size: -1
input_size: 252
interpolation_mode: linear
learning_rate: 0.001
loss: &id001 !!python/object:neuralforecast.losses.pytorch.DistributionLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _base_distribution: !!python/name:torch.distributions.normal.Normal ''
  _buffers: {}
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: {}
  _non_persistent_buffers_set: !!set {}
  _parameters:
    quantiles: !!python/object/apply:torch._utils._rebuild_parameter
    - !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYDQAAADI1MjQ5MDE5MjkxNTJxAlgDAAAAY3B1cQNLA050cQRRLoACXXEAWA0AAAAyNTI0
          OTAxOTI5MTUycQFhLgMAAAAAAAAAAAAAP83MzDyamXk/
      - 0
      - !!python/tuple
        - 3
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  distribution: Normal
  distribution_kwargs: {}
  domain_map: !!python/object/apply:builtins.getattr
  - *id001
  - _domain_map
  has_predicted: false
  horizon_weight: null
  is_distribution_output: true
  num_samples: 1000
  output_names:
  - ''
  - -median
  - !!python/object/apply:numpy._core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADkAAAA1AAAA
  - !!python/object/apply:numpy._core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADkAAAA1AAAA
  outputsize_multiplier: 2
  param_names:
  - -loc
  - -scale
  return_params: false
  scale_decouple: !!python/name:neuralforecast.losses.pytorch.normal_scale_decouple ''
  training: true
lr_scheduler: null
lr_scheduler_kwargs: null
max_steps: 10
mlp_units:
- &id002
  - 512
  - 512
- *id002
- *id002
n_blocks:
- 1
- 1
- 1
n_freq_downsample:
- 4
- 2
- 1
n_pool_kernel_size:
- 2
- 2
- 1
n_samples: 100
n_series: 1
num_lr_decays: 3
optimizer: null
optimizer_kwargs: null
pooling_mode: MaxPool1d
random_seed: 1
scaler_type: robust
stack_types:
- identity
- identity
- identity
start_padding_enabled: false
stat_exog_list: null
step_size: 1
val_check_steps: 100
valid_batch_size: null
valid_loss: null
windows_batch_size: 1024
